name: self
description: The Self package provides utility classes to make it easy
  to create Self extracting executables that ship with resources
  or need to run on boot.
  
version: 0.5.0

environment:
  sdk: ^3.8.0

dependencies:
  dcli: ^8.1.1
  dcli_core: ^8.0.0
  path: ^1.9.1

dev_dependencies:
  args: ^2.7.0
  date_time_format: ^2.0.1
  lint_hard: ^6.1.1
  logging: ^1.3.0
  test: ^1.24.0

platforms:
  linux:
  windows:
  macos:
