name: self
description: The Self package provides utility classes to make it easy 
  to create Self extracting executables that ship with resources
  or need to run on boot.
  
version: 0.0.1

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  dcli: ^7.0.3
  dcli_core: ^7.0.3
  path: ^1.9.1
  # path: ^1.8.0

dev_dependencies:
  args: ^2.7.0
  date_time_format: ^2.0.1
  lint_hard: ^6.1.1
  logging: ^1.3.0
  test: ^1.24.0

platforms: 
  linux:
  windows:
  macos:
